### PR TITLE
add configurable email signature for all outgoing mail notifications

### PR DESCRIPTION
**Pull request by qwertiko**
let me know if this `{!! Config::get('setting.mail_signature') !!}` is no good. I'll then add a mail_stylesheet option, too.

### CODE REVIEW

**Comment by sedan07** [comment]
@qwertiko nice! Looks good to me. `mail_stylesheet` sounds great. Thanks!

**Comment by sedan07** [comment]
will a `mail_stylesheet` work? My knowledge of HTML Email is rather dated but it used to be the case that CSS needed to be inline in HTML emails for it to work reliably. - this might of changed mind.

**Comment by qwertiko** [comment]
This implementation does not strip style attributes from the html or sanitize the mail_signature input in any other way. Neither on saving nor on including in mails.

One could argue with compromised systems injecting stuff into the database. However, a compromised system could also tweak templates. Also, I believe it is fair to trust email clients.

It is possible to sanitize html and require inline css in order to style the signature html stuff, which could be accomplished with a separate mail_stylesheet option. However I would assume that this is not necessary and that this implementation would suffice.

**Comment by sedan07** [comment]
@qwertiko sorry miss read your first comment thought you meant you'd add the css option as well as this, not instead of. :facepalm: 

Yes this looks fine as it is. I'm thinking it should go into a 2.6 branch instead as it's a little more than a patch fix :-), there's a 2.6 branch now created to point this PR at .

**Review by sedan07 — APPROVED** [review]

**Pull request merged**
